### ISSUE TITLE
Apps with multiple startup activities

### ISSUE THREAD

**Issue by molikuner** [markusfisch/PieLauncher#1]
There are apps that define multiple activities with an intent-filter for the launcher:

```XML
<intent-filter>
    <action android:name="android.intent.action.MAIN"/>
    <category android:name="android.intent.category.LAUNCHER"/>
</intent-filter>
```

Would be nice to be able start both activities. Currently the launcher shows just the second one but launches the first one, which is kind of confusing.

**Comment by markusfisch** [comment]
Oh, that's weird indeed! Good catch! 👍 Thanks for filing an issue!

May I ask what app does this so I can debug it? I don't seem to have an app that has multiple launcher activities defined. Of course, I could build one but it would be better to see this bug in its original form 😉

**Comment by molikuner** [comment]
Unfortunately I can't share the app I had in mind while writing this issue, but I have an other app which has the same issue:
https://play.google.com/store/apps/details?id=org.withouthat.acalendar
(Tasks activity may needs to be enabled in the settings manually, but I think it's enabled by default.)

**Comment by markusfisch** [comment]
Found it 😄 Thanks for the sample 👍 Will be fixed in the next version.
