### ISSUE TITLE
DOUBE_SPACE_LAUNCH should be DOUBLE_SPACE_LAUNCH (missing L)

### ISSUE THREAD

**Issue by frank-murphy** [markusfisch/PieLauncher#114]
In file app/src/main/java/de/markusfisch/android/pielauncher/preference/Preferences.java, line 37

DOUBE_SPACE_LAUNCH should be DOUBLE_SPACE_LAUNCH (missing L)

**Comment by markusfisch** [comment]
Ah, good catch! Thank you! 👍 

Fixed in https://github.com/markusfisch/PieLauncher/commit/6baa8499cedc4862a34618a5c0c82215b7cd6158
