### ISSUE TITLE
Option Remove app does not uninstall it

### ISSUE THREAD

**Issue by Stephan-P** [markusfisch/PieLauncher#117]
On my Samsung A41 with Android 12/One UI 4.1 the option Remove takes me to Settings - App info where it is not possible to remove the app from the device. As a result, under Pie Launcher, there is no method left to remove apps from the device.

- Open app drawer
- long press app to be removed
- select option Remove app
- App info opens

**Comment by markusfisch** [comment]
Thanks for filing an issue about this! 👍 

I'm really surprised that the App Info screen does not have an Uninstall button in One UI 4.1 😳

**Comment by Stephan-P** [comment]
I need to take that back.
Earlier I was trying to remove the apps TicketMatic and TicketMaster and the option Remove did not show up in the App info of One UI 4.1.
Prompted by your response I gave it another try with a third app (Energy) and here the option Remove IS available.

Is it possible that certain apps can claim "not to be removed" in Android?

**Comment by markusfisch** [comment]
Ah, I see, I was already wondering how this is possible 😉 

> Is it possible that certain apps can claim "not to be removed" in Android?

Yes, some apps can only be "deactivated" but not removed. But this only applies to pre-installed apps that came with the device. In this case, the "Uninstall" button should read "Deactivate".
