### ISSUE TITLE
Application icons change only after an update of said app or after killing Pile Launcher 

### ISSUE THREAD

**Issue by ShimonHoranek** [markusfisch/PieLauncher#121]
If I have an Icon pack that supports Material You and I change the colors, the icons do not update unless Install an update to the app or I kill Pie Launcher to reload everything. Ideally it should update the icons after each change or at least peridically in the background

**Comment by markusfisch** [comment]
Ah, yes, that's possible because the app doesn't catch any broadcasts when the colors are changed. Thanks for filing an issue about that, and sorry for the late answer (I was on vacation).

Do you mind telling me what Icon pack this is so I can check it works with it?

**Comment by ShimonHoranek** [comment]
I'm using Arcticons Material You

**Comment by markusfisch** [comment]
Fixed in https://github.com/markusfisch/PieLauncher/commit/9a19f8e3d41d4ea84da913a3f93d68a68d3fc314

A new release will be out soon.
