### ISSUE TITLE
[Feature Request] gesture to acces unclosed apps

### ISSUE THREAD

**Issue by MilanJzo** [markusfisch/PieLauncher#128]
Hello There,

i feel like this feature is very basic and therefore it might just be me not being able to figure it out. But i couldnt find any way to open a list of running apps from the home screen. I can work around it by first opening an app and then using the one ui gesture (slowly swiping up), but this is quite annoying. So unless im just not getting it, I'd like to request this feature.

This is a very cool launcher anyways.

I wish you all a good day :)

**Comment by chesio** [comment]
I'm not sure this feature is a launcher responsibility... Personally, I have navigation mode set to 3-button navigation, so I just click on square button to get list of running apps. This works everywhere (home screen inclusive). But I believe different vendor UIs provide different options (I have pure Android).

**Comment by MilanJzo** [comment]
Thats a good point and could be true, but it feels weird to me that using a custom launcher would then prohibit this behaviour when using gesture navigation?

**Comment by MilanJzo** [comment]
By now it seems the gesture works as intended, it just needs to be held way longer than with other launchers (at least in my case). So it mostly seems to be my error. I need to hold the gesture for a full one and a half seconds though, since otherwise it just pulls up the app drawer. Therefore it would be great if the length of the app drawer gesture was customizable. Would this be a launcher responsibility? If so an option to change this duration would be great (there is no option in my vendor settings). Anyways this is a lot better. Thanks for the nudge in the right direction @chesio :)

**Comment by chesio** [comment]
> Therefore it would be great if the length of the app drawer gesture was customizable. Would this be a launcher responsibility? If so an option to change this duration would be great (there is no option in my vendor settings).

There's a [long thread about locking the layout](https://github.com/markusfisch/PieLauncher/issues/67) where touch delay has been mentioned in several comments. There seem to be an accessibility setting called "touch & hold delay" - you might want to experiment with this. As I personally don't use gestures for navigation (except for opening pie menu), I can't really help more...

**Comment by MilanJzo** [comment]
Thank you for your help @chesio , this touch and hold setting is a cool one and useful nonetheless. Sadly it doesn't really help in this case. 

Also ive figured out that this issue is not pie specific but seems to happen with any custom launcher that i currently use. I dont know how, but i never noticed before.

Only the vendor launcher (one ui by samsung) somehow circumvents this issue.

Most of my problems have been solved though. So i guess ill close this issue for now.
