### ISSUE TITLE
hide applications

### ISSUE THREAD

**Issue by theotheroracle** [markusfisch/PieLauncher#13]
the ability to hide applications that you don't want to show up in the app list would be ideal, the easiest way to implement would probably be to add another square to this page 
![image](https://user-images.githubusercontent.com/20211219/115794721-7e0dee80-a39c-11eb-9999-08c3064b4836.png)

**Comment by 2br-2b** [comment]
You'd have to be able to re-show the apps in the settings page

**Comment by theotheroracle** [comment]
you should probably also be able to hide them there too, but this would be a way to quickly do it for new apps or w/e

**Comment by 2br-2b** [comment]
Random idea: you have three options for each app:
1. Shown normally
2. Different icon (#3)
3. Hidden

Maybe also let you add apps to the main page from here?

**Comment by markusfisch** [comment]
Something like this will be in the next upgrading version. I'm in the process of reworking this screen to support hiding apps and also icon packs.

**Comment by wvffle** [comment]
@markusfisch, I can see you've picked up the project once again. Have you considered implementing this?

**Comment by markusfisch** [comment]
Implemented in [version 1.18.0](https://github.com/markusfisch/PieLauncher/releases/tag/1.18.0).
