### ISSUE TITLE
[Feature Proposal] Add support for Fullscreen/Immersive Mode

### ISSUE THREAD

**Issue by Adeor** [markusfisch/PieLauncher#134]
I'd really like to have an option to enable immersive mode. I propose to add "Hide navbar" and "Hide status bar" configuration options (i.e. toggles) similar to KISS launcher. ([Android Docs](https://developer.android.com/develop/ui/views/layout/immersive)).

Use-Case:
I'm using PieLauncher as alternative launcher, while I'm connected to an external display and would like to have a completly dark display, while still being able to run applications through PieLauncher on-demand. With AMOLED theming this is possible for the app itself, but I'd like to have a fully black home screen to prevent screen burn on AMOLED displays.

Alternative Solutions:
Since Android 10 it's not possibly to change this via ADB (`adb shell settings put global policy_control immersive.full=de.markusfisch.android.pielauncher` doesn't work). Therefor I don't think it's possible to overwrite it without root.
With root it's apparently possible with [HideNavBar](https://github.com/Magisk-Modules-Alt-Repo/HideNavBar), but since rooting weakens the android security model, I'd prefer not to do so.

**Comment by markusfisch** [comment]
That's an interesting Use-Case! And because adding an option for this was quite easy, I just did this in https://github.com/markusfisch/PieLauncher/commit/1c465ed69ac4662bf4e3249de0d17124a0706828.

So this will be in the next update!
