### ISSUE TITLE
Only shows the top few apps

### ISSUE THREAD

**Issue by CalmSeeker** [markusfisch/PieLauncher#14]
I have a Pixel XL 3. This app automatically selected the top few apps alphabetically for the pie. I was not able to access any other apps.

**Comment by markusfisch** [comment]
What happens when you just tap the screen like in this video?
https://youtu.be/JM70qf93UqY?t=17

Alternatively you can press Home to open the app list. Does the list open?

**Comment by CalmSeeker** [comment]
Ohhhhh! Thanks. Now I get it.

May 1, 2021, 1:54 PM by ***@***.***:

**Comment by markusfisch** [comment]
You're welcome 😉
