### ISSUE TITLE
put pie in pie as a options

### ISSUE THREAD

**Issue by WAYYYAW** [markusfisch/PieLauncher#143]
while in my arch,it is ok to put a new pie as a options in the main pie。
Slide a finger towards one of the options in the main pie, and the main pie will disappear and then open a new pie.
To more, customize the icons of the options in the pie.
I love this launcher,it's simple but neat and effective.

**Comment by markusfisch** [comment]
Thanks for the idea! And for using the launcher, of course!

Multiple pie menus were requested some times already:
* https://github.com/markusfisch/PieLauncher/issues/129
* https://github.com/markusfisch/PieLauncher/issues/52
* https://github.com/markusfisch/PieLauncher/issues/9

So I will close this issue as duplicate.
