### ISSUE TITLE
Haptic customisation

### ISSUE THREAD

**Issue by veganomy** [markusfisch/PieLauncher#145]
The problem with Pie Launcher's menu, is that it triggers the haptic feedback 3 times.  
1. At initiating the pie
2. At choosing the app
3. At triggering it

When launched an app quickly, this causes vibration motor roar grumpy, that the whole handset shakes.

Triggering 3 times seems overkill. I think the best option is to provide a checkbox menu for all 3 haptic feedbacks.

You can also have a very simple list for haptics just like other configs. Like this for example:
- Disable all feedback
- Only at app trigger
- At app choice and trigger
- At everywhere

A checkbox would be more configurable though. It's all upto you.

_Originally posted by @veganomy in https://github.com/markusfisch/PieLauncher/issues/56#issuecomment-2525197582_

**Comment by markusfisch** [comment]
Implemented in https://github.com/markusfisch/PieLauncher/commit/3b6521375e803c8b007b0f55f04dc5dba089635b

I've added just a yes/no option to disable haptic feedback because there are more places where haptic feedback is fired than just the pie. And because I want to avoid feature creep.

Will be in the next update which will be out very soon.

**Comment by markusfisch** [comment]
Version 1.22.0 is out! Check the settings, in the last section you'll find "Haptic Feedback" now.

**Comment by markusfisch** [comment]
Yes, I think it's best to open a new issue for that so it doesn't get lost, and also to gather more feedback on the topic.

> But I do suggest you to drop one haptic in the pie (while triggering the app launch). It's interfering with the haptic while app selection (where we casually revolve around pie).

This is an accessibility feature. Having a distinct haptic feedback when the pie opens, and another one when you actually select an app, and another one when the app is started, makes it literally possible to use the launcher without looking at the screen.

Of course, not all vibration motors feel the same, and so this may feel like overkill on your device, unfortunately.

**Comment by markusfisch** [comment]
Saw it, tq.

And I _think_ the app is still in the queue on f-droid 🤔 Will keep an eye on it! Thanks for the hint!
