### ISSUE TITLE
Landscape orientation?

### ISSUE THREAD

**Issue by KanadeTachibana2** [markusfisch/PieLauncher#19]
It would be great if this launcher supported landscape mode!

**Comment by markusfisch** [comment]
It's on the list! 😄

Will be a setting once there are settings 😉

**Comment by PoetAnderson1** [comment]
Oh, thank you so much!!

**Comment by LinuxJoeUser** [comment]
Seconded!  Once this is ready, I'll be ready make Pie my regular launcher. :)
