### ISSUE TITLE
Screen doesn't autorotate

### ISSUE THREAD

**Issue by Duoquadragesimal** [markusfisch/PieLauncher#34]
Using a Sony Xperia XZ2 running rooted LineageOS 17.1. Pie launcher doesn't let the screen rotate when autorotate is on and phone orientation changes. So if I go to Pie Launcher when screen is portrait, and I try to rotate to landscape, the screen remains portrait. If I start Pie Launcher with screen in landscape, and rotate my device to portrait, the screen remains in landscape.

**Comment by KneeClass03** [comment]
Using a Fairphone 3 running (unrooted) /e/OS, same thing happens to me. To make the screen rotate, I have to open the application view, which is quite unhandy.

**Comment by markusfisch** [comment]
Sorry, Pie Launcher doesn't support multiple screen rotations at this point 🙈  It will stay in whatever orientation it was initially started in.

Of course, this should be configurable, and it will be at some point.

**Comment by mjray** [comment]
> Sorry, Pie Launcher doesn't support multiple screen rotations at this point see_no_evil It will stay in whatever orientation it was initially started in.

I'm finding it stays in whatever orientation it was last started in, not the initial portrait. If it stayed in the initial orientation all the time (portrait on my phone), I think that would be less confusing.

**Comment by alephalpha0** [comment]
On a Motorola Stylus 5G (2021) and this is happening whenever I use the home gesture when inside a game that forces landscape orientation of the screen.. It remains in landscape for home screen until I reboot my phone.. 😞 this behaviour is irritating me to the point of abandoning using this as my launcher.

**Comment by markusfisch** [comment]
@alephalpha0 Sorry about this 😬 Are you using the latest vesion? Version 1.14.1? Because this really should be fixed now.

If this is happening with 1.14.1 on your device, can you manually choose an orientation in settings (go to the pie editor and tap on the gear icon at the bottom of the screen)?
