### ISSUE TITLE
Can You Make Custom Icon Pack?

### ISSUE THREAD

**Issue by Andre95536** [markusfisch/PieLauncher#35]
Can you make a custom icons for the Pie Launcher? I hope you see this and make update a soon as posible i like the launcher!

**Comment by markusfisch** [comment]
Yes, I plan to add that. However, I don't have a lot of time right now, so it will probably take a little while. Sorry.

**Comment by Andre95536** [comment]
Oh OK I will wait for it

**Comment by gbucar** [comment]
I would like to try to implement this but don't know where to start. I'm not experienced in android development but know java. Could you explain,  where to start?

**Comment by gbucar** [comment]
I would like to try to implement this but don't know where to start. I'm not experienced in android development but know java. Any tips?

**Comment by markusfisch** [comment]
@gbucar Well, you may want to start by searching how to load an icon from an icon pack on Android. There are many other open source launchers that can do this on GitHub. Just search for "github android home screeen launcher support icon pack" or something like that. Then, you could try the search on GitHub to find files with the string "icon pack" or "IconPack". This should give you an idea of how others do it.

In Pie Launcher, there are two places where an icon is loaded, depending on the Android version it's running on. The first one is here, for older Androids:
https://github.com/markusfisch/PieLauncher/blob/master/app/src/main/java/de/markusfisch/android/pielauncher/content/AppMenu.java#L278

And this is executed for newer Android versions (Lollipop or better):
https://github.com/markusfisch/PieLauncher/blob/master/app/src/main/java/de/markusfisch/android/pielauncher/content/AppMenu.java#L315

**Comment by 3r1pm4V13** [comment]
Still wait support icon pack or force all app have same shape icon

**Comment by markusfisch** [comment]
Implemented in [version 1.18.0](https://github.com/markusfisch/PieLauncher/releases/tag/1.18.0).
