### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by rugk** [markusfisch/PieLauncher#4]
It would be great to see this Android app on F-Droid!

[F-Droid](https://f-droid.org/) is an Android app store specifically for free/libre open-source apps. It would be great if your app could be released there, as it is the number one for getting FLOSS Android apps for many people.
F-Droid also builds all apps from source ([optionally even reproducible](https://f-droid.org/en/docs/Reproducible_Builds/)), so downloads from there can be trusted.

The [app developer FAQ](https://f-droid.org/en/docs/FAQ_-_App_Developers/) or [the quick start guide](https://f-droid.org/en/docs/Submitting_to_F-Droid_Quick_Start_Guide/) may help you to get started.

**Comment by fossdd** [comment]
Yup. New MR for this app opened: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/8512

**Comment by TheLastProject** [comment]
It's on F-Droid, just noticed it on there. Very glad to learn about this app, after seeing Binary Eye in F-Droid I expected a simple well-working app and that's exactly what I got :)

**Comment by markusfisch** [comment]
Finally! 😄
