### ISSUE TITLE
I have design New UI ,you can try this Way.

### ISSUE THREAD

**Issue by Oear** [markusfisch/PieLauncher#49]
![sketch1690464188073_edited (1).png](https://github.com/markusfisch/PieLauncher/assets/26364832/02cb8605-b191-4e72-a60d-0c549cac73ee)

![sketch1690469367032.png](https://github.com/markusfisch/PieLauncher/assets/26364832/9fe7dc22-5001-4c17-826e-3163c3ee7a91)

![IMG_20230804_190824.png](https://github.com/markusfisch/PieLauncher/assets/26364832/03fe3b2e-89ca-4546-a2a0-5b33e1ad1868)

![sketch1690469119775.png](https://github.com/markusfisch/PieLauncher/assets/26364832/ad0bd59f-93a9-4f71-98a6-45541b1e4716)

![sketch1690469240693.png](https://github.com/markusfisch/PieLauncher/assets/26364832/e1f70d17-367b-4ea2-830d-f12e4acdf2df)

![sketch1690474661426.png](https://github.com/markusfisch/PieLauncher/assets/26364832/8867f7f2-03e8-49e8-a06a-11b3db404030)

You have to use figma design this New UI.

**Comment by markusfisch** [comment]
Well, thanks for your work on this, but I think this would be an entirely different app 😬 

See, the point of this launcher is that you should be able to launch your most frequently used apps using [muscle memory](https://en.wikipedia.org/wiki/Muscle_memory).

This can only work if the pie menu contains just a handful of icons, so the movement can be _imprecise_ but quick. This is what [Fitts's Law](https://en.wikipedia.org/wiki/Fitts%27s_law) is about.

So the idea is that the number of your most frequently used apps is small enough for a pie menu you can use without thinking.

But this is open source for a reason! 😉 Of course, you're free to fork this project and change this to your liking.
