### ISSUE TITLE
Want to add dynamic background

### ISSUE THREAD

**Issue by Oear** [markusfisch/PieLauncher#51]
Help me, I can't seem to find the main interface of the application. The layout home seems to be transparent and cannot add dynamic wallpaper. Please tell me where to add the layout of dynamic wallpaper.

**Comment by markusfisch** [comment]
I suppose you want to change the wallpaper? If so, simply use your phone's settings to set the wallpaper.

This launcher doesn't have a menu for this.

**Comment by Oear** [comment]
I want pie launcher growing great！
Where is backgroud layout？
