### ISSUE TITLE
Feature Request: Vibration/haptics setting

### ISSUE THREAD

**Issue by supasonix-zuv** [markusfisch/PieLauncher#56]
Would it be possible to add a vibrate option when changing which app is being hovered over? Example: long press to open pie menu, hover over sms app, haptic activates, switch to hovering over web browser, haptic activates. I'd suggest a fairly short length, like how the vibrate works on an on-screen keyboard, but a customizable setting would obviousy be more flexible. Thanks for the great app!

**Comment by markusfisch** [comment]
Yes, this would be possible! And in fact I've already tried this when I was adding support for haptic feedback. I just thought this would be too much. But now, since you're asking for it, I think I will add this as an option in the app's settings.

Right now there are only vibrations when "Touch Feedback" is enabled in "Accessibility" > "Vibration & haptic strength".

**Comment by markusfisch** [comment]
@foxjaw The vibrations should be very subtle - so much that you're hardly able to notice them in everyday noises. Are they stronger than that on your device?

**Comment by jarusaurus** [comment]
I seem to have lost the vibration once Updated to the latest version. Also updated to OxygenOS 14 so not sure if it was the os version bump that did it. I don't see the touch feedback option in accessibility options. 

It kind of auto worked previously. 
Help if possible please.

**Comment by markusfisch** [comment]
@jarusaurus Sorry, this must be a problem with OxygenOS 14 since there was no change regarding vibration/haptic feedback since version 1.14.2, and this just added haptic feedback for pie selection.

**Comment by jarusaurus** [comment]
Thanks.. I am not happy with the change, but unfortunately nothing to do I guess.

> Right now there are only vibrations when "Touch Feedback" is enabled in "Accessibility" > "Vibration & haptic strength".
I did look for this option but couldn't find it at all on OxygenOS14, must be the flavour pack by Oneplus.

Couldn't find any other option to enable or disable. 
I wonder what made it work under OxygenOs 13?? it worked fine then.

**Comment by markusfisch** [comment]
@jarusaurus [Apparently](https://www.rmupdate.com/2023/10/17/these-oneplus-devices-support-o-haptics-feature-list/), touch feedback is called "O-haptics" on OnePlus devices. This seems to be an extended, proprietary feature.

Does this work on your device? (taken from the above link)

1. Go to the device’s Settings 
2. Scroll down and tap on the Sound & vibration
3. Select Haptics and tones 
4. Here you will see the O-haptics feature
5. Turn on the System haptics toggle

Unfortunately, I don't have a OnePlus device and cannot test this myself yet.

**Comment by jarusaurus** [comment]
> Does this work on your device? (taken from the above link)
Hi Markus,
Thanks a lot for that. I had already setup O-haptics on my Oneplus. 
But sadly toggling that had no change. 
I believe Oneplus made some change to this feature with their OxygenOS 14. 
I have the latest PL installed but still don't have the haptic feedback on rolling over the icons. 
I can live with that. 
Not sure if any future updates ( both Oplus as well yours) will help. 
*fingerscrossed*

Thanks a lot for the recent updates to the launcher. Loving every update bump.
Looking forward for future.
Regards

**Comment by markusfisch** [comment]
Yes, this is already implemented. I will close this issue.

And yes, of course, it's possible to add a toggle option in the launcher settings - I just assumed that anybody who enabled haptic feedback in the system settings would implicitly and always want this for the launcher, too. But apparantly you would want to disable it in the laucher but keep it for everything else?

**Comment by markusfisch** [comment]
Ah, now I understand. I will add an option to the app settings with the next version.
