### ISSUE TITLE
Make pie configuration screen easier to find

### ISSUE THREAD

**Issue by einmeterhecht** [markusfisch/PieLauncher#59]
As a new user, it took me quite some time to find the screen where you can configure the app pie. Dragging a random app from the app list on the cancel button seems too hacky to be the only way to get there. Any ideas where to show a settings button?

**Comment by Aiz0** [comment]
I think a good spot could be next to the search field. having an icon in the top right corner.

**Comment by einmeterhecht** [comment]
Perfect, thanks!
