### ISSUE TITLE
Configuration difficult on small screen

### ISSUE THREAD

**Issue by SurmanPP** [markusfisch/PieLauncher#64]
On phones with small screens(3.2 inches for me) the configuration of the launcher is difficult. As you can see below the pie menu is obstructing the menu buttons. I see two possible options:
1. Move the buttons to the bottom.
2. My preferred option: Some older phones seem to have a menu button instead of an activities button. Mine is one of them and I'd really like it if this project made use of it.

Here is a demonstration of the problem:
![screenshot](https://github.com/markusfisch/PieLauncher/assets/70163032/c987ca1e-319c-41cf-bd04-2f250ed70412)
None of the buttons are easy to hit.

**Comment by SurmanPP** [comment]
The second option seems like it would be implemented using [Activity.onCreateOptionsMenu](https://developer.android.com/reference/android/app/Activity.html#onCreateOptionsMenu(android.view.Menu)). Would be nice if it was an option at least.

**Comment by markusfisch** [comment]
Ah, thanks for filing an issue about this! 👍 

The positioning of the buttons is definitely wrong… I will fix this with the next release!

And I will also check if I can add a menu for the menu button.

**Comment by markusfisch** [comment]
Version [1.16.0](https://github.com/markusfisch/PieLauncher/releases/tag/1.16.0) improves the pie editor layout for small screens. Should become available on Google Play in the next few hours.

**Comment by SurmanPP** [comment]
Thank you very much! Almost forgot closing...
