### ISSUE TITLE
Pixel Fold - Outside screen always in landscape

### ISSUE THREAD

**Issue by devilsclaw** [markusfisch/PieLauncher#65]
When the Fold is open auto rotate works. When the fold is closed the lock screen looks correct. Once unlocked the outside screen will not auto rotate and is alway in landscape.

**Comment by markusfisch** [comment]
Oh, sorry about this - I don't have a folding device for testing around yet, but I will sure look into it! 

The launcher doesn't really support auto rotation at the moment, and this may be the cause for this bug 🤔

**Comment by devilsclaw** [comment]
I looked to see if there is a build guide for this project I might of missed it. I could look into it since I am also a coder. What is the best way to build for this project. I primarily work and code in Linux and I have built and patched LineageOS in the past for one of my devices. Which SDK version do you use to compile against.

**Comment by markusfisch** [comment]
No, unfortunately there's no build guide (yet), but all you need is [Android Studio](https://developer.android.com/studio) essentially. The easiest way is to install it and open the project with it. It should immediately build (once the Android SDK is downloaded, which should happen automatically).

It's also possible to build the project _without_ Android Studio, in which case you would need to download and install the Android [SDK tools](https://developer.android.com/tools) manually. After that, you can simply use the `Makefile` in this repository to build and run the project.

**Comment by markusfisch** [comment]
Version [1.16.0](https://github.com/markusfisch/PieLauncher/releases/tag/1.16.0) adds an orienation option for auto-rotation (in the settings). Could you please try this and tell me if this works better with a folding device?

The new version should be available soon on Google Play, too.

**Comment by devilsclaw** [comment]
Initially this looked like it work on the outside screen. Then when I went into the inside larger screen it clipped the sides. Then I went into settings and had to set the orientation from portrait to auto and everything worked. thanks.
