### ISSUE TITLE
notification bar is black

### ISSUE THREAD

**Issue by GreenArchiveForever** [markusfisch/PieLauncher#70]
i got problem here app is working on A11 but notification bar is black
![Screenshot_20231229-151920.png](https://github.com/markusfisch/PieLauncher/assets/136427398/31a85a6e-7d9e-41b0-9a72-6f5bb229186e)

is there a way that you can do to fix this?

Realme C21Y A11 RUI 1.0
RMX 2030
Pie Launcher version 1.16.0 f-droid release

**Comment by markusfisch** [comment]
Sorry for not replying sooner, I must have overlooked this issue somehow 🙈 

Unfortunately, the navigation bar cannot be made completely transparent on all versions of Android.
