### ISSUE TITLE
The launcher keeps crashing when searching for an app

### ISSUE THREAD

**Issue by romain030992** [markusfisch/PieLauncher#76]
Hi, 

The reproducing steps for the crashes are
1. Single tap to open the apps drawer
2. Start typing 

The app crashes instantly... 
It's the same behavior if I try to scroll in the app drawer. 

App version 1.17.5
Android 8.1.0
Samsung Note 9

Do nit hesitate if you need more info. I really love this launcher and I would be happy to help !

**Comment by markusfisch** [comment]
Thanks for filing an issue about this! Very strange! 😳 Unfortunately, I have no idea what's causing this 🙈 

Did a previous version work?

**Comment by markusfisch** [comment]
Hm, I just checked [Vitals](https://developer.android.com/topic/performance/vitals) and saw this exception:

```
Exception java.lang.RuntimeException: Canvas: trying to draw too large(115605504bytes) bitmap.
  at android.view.DisplayListCanvas.throwIfCannotDraw (DisplayListCanvas.java:229)
  at android.view.RecordingCanvas.drawBitmap (RecordingCanvas.java:97)
  at de.markusfisch.android.pielauncher.widget.AppPieView.drawList (AppPieView.java:1)
  …
```

`android.view.RecordingCanvas` is the system screen recorder. Did you try to record the crash or can this be the root cause for the crash? 🤔

**Comment by romain030992** [comment]
No I didn't try to record the crash
Yes it was working in previous versions but I don't know from which version the crash started to occur... I can downgrade step by step to identify the version which introduced the issue if you want

**Comment by romain030992** [comment]
I rollbacked step by step to 1.13.0 and I still have the issue... i have no clue what's happening! Is there anything I can do so you have more logs to investigate ? Maybe it's related to something I did recently on my device but I cant remember something special...

**Comment by markusfisch** [comment]
Hm, well, you could check the device logs with [logcat](https://developer.android.com/tools/logcat) or [Android Studio](https://developer.android.com/studio), if you really want to dive into it. There you will find the exact exception that is crashing the app, which may well be that RuntimeException I posted earlier:
```
Exception java.lang.RuntimeException: Canvas: trying to draw too large(115605504bytes) bitmap.
  at android.view.DisplayListCanvas.throwIfCannotDraw (DisplayListCanvas.java:229)
  at android.view.RecordingCanvas.drawBitmap (RecordingCanvas.java:97)
  at de.markusfisch.android.pielauncher.widget.AppPieView.drawList (AppPieView.java:1)
  …
```

If this is indeed the exception, then there must be some kind of screen recording going on, I guess 🤔 

Silly question: Have you tried rebooting the device?

**Comment by romain030992** [comment]
Yes of course I tried to reboot several times but the issue is sill here. Thanks for the exception, I'm going to dive into it further I think.

**Comment by romain030992** [comment]
Ok it's working now. I fixed the issue! 
It was related to an application I installed earlier. I did some research related to the exception you described and it appears that it is related to the resources which are in the wrong folder (drawable instead of drawable-xxhdpi. Because the issue happened last week I supposed that I installed an app which was managing its resources wrong. So when I try to go through the apps in the launcher, the app crashes when it tries to display the app. I found the app, removed it and everything works now ! Thanks for your help 🙃

**Comment by markusfisch** [comment]
Ah, I see! Great find! 👍 And happy you found what was causing the issue!

But the launcher really shouldn't crash for such a misbehaving app, of course, and I will check if I can handle this somehow. May I ask what app it was so I can use it for debugging?

**Comment by romain030992** [comment]
Indeed it would be better not to crash. 
The app is "Direct Assurance"  (https://www.direct-assurance.fr/nos-services/appli-mobile-direct-assurance) 

I noticed there is no issue with the default launcher ans when I navigate through the app from the smartphone settings. Maybe they handle it differently.

**Comment by markusfisch** [comment]
Right 👍 

And thanks again @romain030992 for your help!

The size of the icons is now limited, and so this should no longer be possible.
