### ISSUE TITLE
Feature Request: Hide apps

### ISSUE THREAD

**Issue by FrostyCirno** [markusfisch/PieLauncher#77]
It would be great to hide apps from the app drawer. I have switched messaging apps, but I do not want to delete the stock app.

**Comment by markusfisch** [comment]
It's on the feature list! 👍

**Comment by markusfisch** [comment]
Implemented in [version 1.18.0](https://github.com/markusfisch/PieLauncher/releases/tag/1.18.0).

**Comment by xi7** [comment]
why not just click hidden apps and select quickly.

drag and drop is slow and unnecessary

**Comment by markusfisch** [comment]
@xi7 In the settings, choose `Long press` -> `Show pop-up menu` to disable Drag'n Drop and show a pop-up menu instead.
