### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by fapper22** [markusfisch/PieLauncher#79]
On a rooted A53. Link in F-Droid does not work-

**Comment by markusfisch** [comment]
Sorry for that, but that's an issue for f-droid, I'm afraid 😉 

Alternatively, you can also get the app directly from GitHub here:
https://github.com/markusfisch/PieLauncher/releases

Please note that f-droid is using its own signature which makes the f-droid installation incompatible to the one in Google Play or that from GitHub.
