### ISSUE TITLE
The app if used as an assistant app is closed in the background

### ISSUE THREAD

**Issue by darhma** [markusfisch/PieLauncher#8]
I have a phone with lineageos 17.1 (android 10) and am currently trying to use pie launcher as an assistant app.

I'm getting along pretty well, the only problem I've encountered is that when I call up the app (even with battery optimization turned off) after a while of not using it I get the "loading" screen and have to wait a few seconds before I can use it. 

Is there any way to keep the app constantly active? Maybe adding an option to enable a persistent notification?

**Comment by markusfisch** [comment]
Hm, a foreground notification might be an option, but it still wouldn't guarantee that the app wont be terminated by the system. Unfortunately - but intentionally - it's quite hard for an app to stay in memory.

Did you disable battery optimization just from the dialog of the app? Are there more options in Settings -> Apps -> Battery Optimization?

**Comment by darhma** [comment]
I disabled battery optimization and checked for other options. 
___
I have many apps installed (almost all from f-droid since I don't use google services) and the ones that require to stay active in the background normally use persistent notification (which can be hidden) and work fine. Some of these apps are: waveup, conversations, delta chat, jami, kde connect, proximity sensor fix and telegram. 
___
That's why I thought that persistent notification could be a solution. I understand that it might be annoying in case you use pie launcher as default launcher and not as an assistant app so I thought to make it optional, but since the app doesn't have any other settings it might not be an optimal solution. 
___
I'm not a programmer but I imagine that the reason for the wait is due to the loading of the list of all applications, in this case maybe you could think of not loading the applications at startup but only when you open the search screen for the first time: in this way you would have the applications selected for the quick start immediately available. 
___
I find the application overall well done and that the idea behind it is valid, and I also understand that my use case is probably not the one originally intended. Unfortunately, not being a developer, I don't know how to contribute code and I also don't know if my suggestions are useful or applicable. In any case I will continue to follow with interest the development of the application. Thanks

**Comment by darhma** [comment]
Update: I've noticed that if I set pie launcher as both default launcher and assistant launcher and then select as default launcher the one I usually use the problem doesn't occur anymore.

I leave to you the decision whether to close this report or not, as the problem is present but easily fixable (the workaround is still needed every time you reboot the phone).

Since I do not reboot the phone very often and the workaround is really simple and fast for me the report can be closed, but maybe this last information may be useful to understand how to solve the problem, which I do not exclude may depend on the custom rom (in this case you should try to replicate the problem with other devices).

I'm very happy to have found this alternative solution because the suggestions I had proposed anyway did not convince me to the end.

Thanks for your work on this app

**Comment by markusfisch** [comment]
Thanks for the update and the detailed description of the workaround! 👍 

I'm already considering caching the list of applications to speed up start time, since there are more edge cases in which that may matter. The list is already updated in the background once it's loaded so it's just the inital loading that keeps the user waiting. So maybe this will change with the next update.

Thanks for using the app and contributing to it!
