### ISSUE TITLE
"Auto start perfect matches" only launches on the next text change

### ISSUE THREAD

**Issue by einmeterhecht** [markusfisch/PieLauncher#86]
Newly introduced in version 1.17.4

Steps to reproduce:
- Turn on "Auto start perfect matches" in the settings
- Open the app list
- Start typing the name of an app, until it is the only app that shows up

Expected behaviour:
- App should be launched automatically
Observed behaviour:
- App is only launched when the next character is typed

Reason:
`updateAppList()` is only called *after* the check if only one app matches the query
This has changed in 1.17.4 - See `HomeActivity` in https://github.com/markusfisch/PieLauncher/commit/9fd7110c044762752bb5591115fc4585e59dc041

Potential Fix:
- Move `updateAppList();` before the `if (endsWithDoubleSpace ||...` condition:
https://github.com/markusfisch/PieLauncher/blob/4a2bc5562c38ba85ec2dc1ab634ad29465410b17/app/src/main/java/de/markusfisch/android/pielauncher/activity/HomeActivity.java#L215-L220

**Comment by markusfisch** [comment]
Ah, sorry for messing this up 🙈 

Fixed in https://github.com/markusfisch/PieLauncher/commit/76dca68227181cf7c3986ba0ec41c2e95c4ef2d9
