### ISSUE TITLE
Follow android defaults for animations

### ISSUE THREAD

**Issue by foxjaw** [markusfisch/PieLauncher#90]
When an app is opened, launcher makes ripple effects & other animations.  
I either expect a toggle in the settings that disables or enables it, or let the launcher follow the default settings of android.  
Personally, I wanna disable such feedbacks, as they won't matter to me.

**Comment by markusfisch** [comment]
Hm, this is (a variation) of the omnipresent [Ripple effect](https://m3.material.io/foundations/interaction/states/applying-states#bb39aa13-bbcf-400d-a094-2cd2b7aebcc2) on Android.

I wonder if it's just too hard, too visible? This ripple feedback is used in many places in the app (for example when you start an app from the drawer, in the editor, on buttons…). Would you like to disable it there too or is it just the feedback from the pie menu?

**Comment by markusfisch** [comment]
Ah, I see! Yes, this definitely makes sense! 👍 Thanks for bringing my attention to this! The next update will follow the default settings.

**Comment by markusfisch** [comment]
Yes, this will be included too! 👍

**Comment by markusfisch** [comment]
Implemented in https://github.com/markusfisch/PieLauncher/commit/77f5f34eb9845d91eb8dc2472b79ac85c2ed4f09

And there's already a new version, [1.18.4](https://github.com/markusfisch/PieLauncher/releases/tag/1.18.4), that includes this change. Should become available on f-droid soon, too.
